name: Question
description: Ask a question about kount
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: What version of kount are you using? (see `kount --version`)
      placeholder: e.g., kount 0.1.0
    validations:
      required: false
